
 
 
 



 

#!/bin/sh

# Clean up the results directory
rm -rf results
mkdir results

#Synthesize the Wrapper Files

echo 'Synthesizing example design with XST';
xst -ifn xst.scr
cp BRAM_COEFF_exdes.ngc ./results/


# Copy the netlist generated by Coregen
echo 'Copying files from the netlist directory to the results directory'
cp ../../BRAM_COEFF.ngc results/

#  Copy the constraints files generated by Coregen
echo 'Copying files from constraints directory to results directory'
cp ../example_design/BRAM_COEFF_exdes.ucf results/

cd results

echo 'Running ngdbuild'
ngdbuild -p xc6vlx240t-ff1156-1 BRAM_COEFF_exdes

echo 'Running map'
map BRAM_COEFF_exdes -o mapped.ncd -pr i

echo 'Running par'
par mapped.ncd routed.ncd

echo 'Running trce'
trce -e 10 routed.ncd mapped.pcf -o routed

echo 'Running design through bitgen'
bitgen -w routed

echo 'Running netgen to create gate level Verilog model'
netgen -ofmt verilog -sim -tm BRAM_COEFF_exdes -pcf mapped.pcf -w -sdf_anno false routed.ncd routed.v
